# Block packages younger than 7 days as a supply-chain defense.
# https://daniakash.com/posts/simplest-supply-chain-defense/
minimumReleaseAge: 10080

allowBuilds:
  esbuild: true
  lefthook: true
  workerd: true
